spring:
  config:
    activate:
      on-profile: local
    profiles:
      active: local
  application:
    name: metrics-producer
  mvc:
    servlet:
      path: /api
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
# Swagger documentation
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    doc-expansion: none
server:
  port: 8082